"""
Django settings for lernplattform project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8$_og51)4vvh^2+vc-mjlo=ol%9w4@%@q)0l8=@rnb4p88+-^e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'quiz',
    'courses',
    'exams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lernplattform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lernplattform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'outdent', 'indent', '|',
            'link', 'insertTable', 'blockQuote', '|',
            'undo', 'redo', 'removeFormat', '|',
            'sourceEditing'
        ],
        'height': '650px',
        'language': 'de',
        'htmlSupport': {
            'allow': [
                {
                    'name': '/.*/',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
            ],
        },
    },
}

# Code question guardrails (server-side execution hardening).
CODE_EXECUTION_ENABLED = True
CODE_EXECUTION_MAX_SOURCE_CHARS = 8000
CODE_EXECUTION_MAX_STDIN_CHARS = 4000
CODE_EXECUTION_MAX_EXPECTED_OUTPUT_CHARS = 6000
CODE_EXECUTION_MAX_STDOUT_CHARS = 6000
CODE_EXECUTION_MAX_STDERR_CHARS = 6000
CODE_EXECUTION_PYTHON_TIMEOUT_SECONDS = 3
CODE_EXECUTION_CPP_COMPILE_TIMEOUT_SECONDS = 8
CODE_EXECUTION_CPP_RUN_TIMEOUT_SECONDS = 3

CODE_EXECUTION_BLOCKED_PATTERNS = {
    "python": [
        "import os",
        "from os",
        "import subprocess",
        "from subprocess",
        "import socket",
        "from socket",
        "import ctypes",
        "from ctypes",
        "import pathlib",
        "from pathlib",
        "open(",
        "__import__(",
        "eval(",
        "exec(",
    ],
    "cpp": [
        "std::system",
        "system(",
        "popen(",
        "_popen(",
        "createprocess",
        "shellexecute",
        "winexec",
        "#include <filesystem>",
        "#include <fstream>",
        "#include <thread>",
    ],
}

# Topic PDF OCR settings (Admin Topic editor)
TOPIC_OCR_MAX_FILE_MB = 20
TOPIC_OCR_MAX_PAGES = 40
TOPIC_OCR_DPI = 300
TOPIC_OCR_LANG = "deu+eng"
TOPIC_OCR_MAX_TEXT_CHARS = 120000
# Optional absolute paths on Windows if binaries are not in PATH.
TOPIC_OCR_TESSERACT_CMD = "C:/Program Files/Tesseract-OCR/tesseract.exe"
TOPIC_OCR_POPPLER_PATH = "C:/Users/xanta/AppData/Local/Microsoft/WinGet/Packages/oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe/poppler-25.07.0/Library/bin"
TOPIC_OCR_TESSDATA_DIR = str(BASE_DIR / 'tessdata')

LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
CSRF_FAILURE_VIEW = "quiz.views.csrf_failure"