# Generated by Django 6.0.3 on 2026-03-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(help_text='Rückseite der Karte (Antwort/Erklärung)'),
        ),
        migrations.CreateModel(
            name='FlashcardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Optionstext', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Dies ist die richtige Antwort')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.flashcard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
